export const GET_CAPITAL_WEATHER_START = 'GET_CAPITAL_WEATHER_START';
export const GET_CAPITAL_WEATHER_SUCCESS = 'GET_CAPITAL_WEATHER_SUCCESS';
export const GET_CAPITAL_WEATHER_FAILURE = 'GET_CAPITAL_WEATHER_FAILURE';